<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientNutritionSeeder extends Seeder
{
    public function run(): void
    {
        // ✓ macros per GRAM (divide per 100g values by 100)
        $ingredients = [
            // PROTEÍNAS
            ['title' => 'Pechuga de pollo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.65, 'protein_per_gram' => 0.31, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.036, 'status' => 1],
            ['title' => 'Pollo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.65, 'protein_per_gram' => 0.31, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.036, 'status' => 1],
            ['title' => 'Pavo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.35, 'protein_per_gram' => 0.30, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Ternera', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.97, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.10, 'status' => 1],
            ['title' => 'Cerdo', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.42, 'protein_per_gram' => 0.27, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.14, 'status' => 1],
            ['title' => 'Cordero', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.82, 'protein_per_gram' => 0.25, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.20, 'status' => 1],
            ['title' => 'Conejo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.36, 'protein_per_gram' => 0.28, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.023, 'status' => 1],
            ['title' => 'Carne picada', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.50, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.20, 'status' => 1],
            ['title' => 'Jamón serrano', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.40, 'protein_per_gram' => 0.33, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.12, 'status' => 1],
            ['title' => 'Jamón', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.45, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0.01, 'fat_per_gram' => 0.07, 'status' => 1],
            ['title' => 'Tocino', 'ingredient_category_id' => 1, 'calories_per_gram' => 5.41, 'protein_per_gram' => 0.11, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.56, 'status' => 1],
            ['title' => 'Bacon', 'ingredient_category_id' => 1, 'calories_per_gram' => 5.41, 'protein_per_gram' => 0.11, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.56, 'status' => 1],
            ['title' => 'Chorizo', 'ingredient_category_id' => 1, 'calories_per_gram' => 4.55, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.38, 'status' => 1],
            ['title' => 'Salchicha', 'ingredient_category_id' => 1, 'calories_per_gram' => 3.00, 'protein_per_gram' => 0.14, 'carbs_per_gram' => 0.01, 'fat_per_gram' => 0.27, 'status' => 1],

            // PESCADOS
            ['title' => 'Salmón', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.08, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.13, 'status' => 1],
            ['title' => 'Atún', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.44, 'protein_per_gram' => 0.23, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.06, 'status' => 1],
            ['title' => 'Merluza', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.89, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.018, 'status' => 1],
            ['title' => 'Bacalao', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.82, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Sardina', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.08, 'protein_per_gram' => 0.25, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.11, 'status' => 1],
            ['title' => 'Gamba', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.00, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Langostino', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.00, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Camarón', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.00, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Pulpo', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.82, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Calamar', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.92, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.019, 'status' => 1],
            ['title' => 'Mejillón', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.86, 'protein_per_gram' => 0.12, 'carbs_per_gram' => 0.04, 'fat_per_gram' => 0.022, 'status' => 1],
            ['title' => 'Almeja', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.74, 'protein_per_gram' => 0.13, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Pescado', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.20, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],

            // HUEVOS Y LÁCTEOS
            ['title' => 'Huevo', 'ingredient_category_id' => 5, 'calories_per_gram' => 1.55, 'protein_per_gram' => 0.13, 'carbs_per_gram' => 0.011, 'fat_per_gram' => 0.11, 'status' => 1],
            ['title' => 'Huevos', 'ingredient_category_id' => 5, 'calories_per_gram' => 1.55, 'protein_per_gram' => 0.13, 'carbs_per_gram' => 0.011, 'fat_per_gram' => 0.11, 'status' => 1],
            ['title' => 'Clara de huevo', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.52, 'protein_per_gram' => 0.11, 'carbs_per_gram' => 0.007, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Leche', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.61, 'protein_per_gram' => 0.032, 'carbs_per_gram' => 0.048, 'fat_per_gram' => 0.035, 'status' => 1],
            ['title' => 'Leche entera', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.61, 'protein_per_gram' => 0.032, 'carbs_per_gram' => 0.048, 'fat_per_gram' => 0.035, 'status' => 1],
            ['title' => 'Nata', 'ingredient_category_id' => 5, 'calories_per_gram' => 2.92, 'protein_per_gram' => 0.021, 'carbs_per_gram' => 0.032, 'fat_per_gram' => 0.30, 'status' => 1],
            ['title' => 'Queso', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.50, 'protein_per_gram' => 0.25, 'carbs_per_gram' => 0.01, 'fat_per_gram' => 0.27, 'status' => 1],
            ['title' => 'Queso parmesano', 'ingredient_category_id' => 5, 'calories_per_gram' => 4.31, 'protein_per_gram' => 0.38, 'carbs_per_gram' => 0.04, 'fat_per_gram' => 0.30, 'status' => 1],
            ['title' => 'Queso mozzarella', 'ingredient_category_id' => 5, 'calories_per_gram' => 2.80, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.20, 'status' => 1],
            ['title' => 'Mozzarella', 'ingredient_category_id' => 5, 'calories_per_gram' => 2.80, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.20, 'status' => 1],
            ['title' => 'Queso fresco', 'ingredient_category_id' => 5, 'calories_per_gram' => 1.60, 'protein_per_gram' => 0.14, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.11, 'status' => 1],
            ['title' => 'Requesón', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.98, 'protein_per_gram' => 0.11, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.05, 'status' => 1],
            ['title' => 'Yogur', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.61, 'protein_per_gram' => 0.035, 'carbs_per_gram' => 0.047, 'fat_per_gram' => 0.033, 'status' => 1],
            ['title' => 'Yogur griego', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.97, 'protein_per_gram' => 0.10, 'carbs_per_gram' => 0.04, 'fat_per_gram' => 0.05, 'status' => 1],
            ['title' => 'Mantequilla', 'ingredient_category_id' => 6, 'calories_per_gram' => 7.17, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.001, 'fat_per_gram' => 0.81, 'status' => 1],

            // VERDURAS Y HORTALIZAS
            ['title' => 'Tomate', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.18, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.039, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Cebolla', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.40, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.093, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Ajo', 'ingredient_category_id' => 2, 'calories_per_gram' => 1.49, 'protein_per_gram' => 0.064, 'carbs_per_gram' => 0.33, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Pimiento', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.20, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.046, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Pimiento rojo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.31, 'protein_per_gram' => 0.01, 'carbs_per_gram' => 0.06, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Pimiento verde', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.20, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.046, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Zanahoria', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.41, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.096, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Calabacín', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.17, 'protein_per_gram' => 0.012, 'carbs_per_gram' => 0.031, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Berenjena', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.25, 'protein_per_gram' => 0.01, 'carbs_per_gram' => 0.059, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Brócoli', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.34, 'protein_per_gram' => 0.028, 'carbs_per_gram' => 0.07, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Coliflor', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.25, 'protein_per_gram' => 0.019, 'carbs_per_gram' => 0.05, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Espinaca', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.23, 'protein_per_gram' => 0.029, 'carbs_per_gram' => 0.036, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Acelga', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.19, 'protein_per_gram' => 0.018, 'carbs_per_gram' => 0.037, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Lechuga', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.15, 'protein_per_gram' => 0.014, 'carbs_per_gram' => 0.029, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Pepino', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.16, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.036, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Champiñón', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.22, 'protein_per_gram' => 0.031, 'carbs_per_gram' => 0.033, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Setas', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.22, 'protein_per_gram' => 0.031, 'carbs_per_gram' => 0.033, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Apio', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.16, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Puerro', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.61, 'protein_per_gram' => 0.015, 'carbs_per_gram' => 0.14, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Judías verdes', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.31, 'protein_per_gram' => 0.018, 'carbs_per_gram' => 0.07, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Guisante', 'ingredient_category_id' => 7, 'calories_per_gram' => 0.81, 'protein_per_gram' => 0.054, 'carbs_per_gram' => 0.14, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Espárrago', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.20, 'protein_per_gram' => 0.022, 'carbs_per_gram' => 0.039, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Alcachofa', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.47, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.10, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Remolacha', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.016, 'carbs_per_gram' => 0.096, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Col', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.25, 'protein_per_gram' => 0.013, 'carbs_per_gram' => 0.058, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Calabaza', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.26, 'protein_per_gram' => 0.01, 'carbs_per_gram' => 0.065, 'fat_per_gram' => 0.001, 'status' => 1],

            // CEREALES, LEGUMBRES, TUBÉRCULOS
            ['title' => 'Arroz', 'ingredient_category_id' => 4, 'calories_per_gram' => 1.30, 'protein_per_gram' => 0.027, 'carbs_per_gram' => 0.28, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Arroz blanco', 'ingredient_category_id' => 4, 'calories_per_gram' => 1.30, 'protein_per_gram' => 0.027, 'carbs_per_gram' => 0.28, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Pasta', 'ingredient_category_id' => 4, 'calories_per_gram' => 1.31, 'protein_per_gram' => 0.05, 'carbs_per_gram' => 0.25, 'fat_per_gram' => 0.011, 'status' => 1],
            ['title' => 'Macarrones', 'ingredient_category_id' => 4, 'calories_per_gram' => 1.31, 'protein_per_gram' => 0.05, 'carbs_per_gram' => 0.25, 'fat_per_gram' => 0.011, 'status' => 1],
            ['title' => 'Espaguetis', 'ingredient_category_id' => 4, 'calories_per_gram' => 1.31, 'protein_per_gram' => 0.05, 'carbs_per_gram' => 0.25, 'fat_per_gram' => 0.011, 'status' => 1],
            ['title' => 'Fideos', 'ingredient_category_id' => 4, 'calories_per_gram' => 1.31, 'protein_per_gram' => 0.05, 'carbs_per_gram' => 0.25, 'fat_per_gram' => 0.011, 'status' => 1],
            ['title' => 'Pan', 'ingredient_category_id' => 4, 'calories_per_gram' => 2.65, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.49, 'fat_per_gram' => 0.032, 'status' => 1],
            ['title' => 'Pan integral', 'ingredient_category_id' => 4, 'calories_per_gram' => 2.47, 'protein_per_gram' => 0.13, 'carbs_per_gram' => 0.41, 'fat_per_gram' => 0.034, 'status' => 1],
            ['title' => 'Avena', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.89, 'protein_per_gram' => 0.169, 'carbs_per_gram' => 0.66, 'fat_per_gram' => 0.069, 'status' => 1],
            ['title' => 'Patata', 'ingredient_category_id' => 4, 'calories_per_gram' => 0.77, 'protein_per_gram' => 0.02, 'carbs_per_gram' => 0.17, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Boniato', 'ingredient_category_id' => 4, 'calories_per_gram' => 0.86, 'protein_per_gram' => 0.016, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Batata', 'ingredient_category_id' => 4, 'calories_per_gram' => 0.86, 'protein_per_gram' => 0.016, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Harina', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.64, 'protein_per_gram' => 0.10, 'carbs_per_gram' => 0.76, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Harina de trigo', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.64, 'protein_per_gram' => 0.10, 'carbs_per_gram' => 0.76, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Maíz', 'ingredient_category_id' => 4, 'calories_per_gram' => 0.86, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.19, 'fat_per_gram' => 0.009, 'status' => 1],
            ['title' => 'Lentejas', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.16, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Garbanzo', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.39, 'protein_per_gram' => 0.089, 'carbs_per_gram' => 0.27, 'fat_per_gram' => 0.026, 'status' => 1],
            ['title' => 'Alubia', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.27, 'protein_per_gram' => 0.084, 'carbs_per_gram' => 0.23, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Judía', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.27, 'protein_per_gram' => 0.084, 'carbs_per_gram' => 0.23, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Frijol', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.27, 'protein_per_gram' => 0.084, 'carbs_per_gram' => 0.23, 'fat_per_gram' => 0.005, 'status' => 1],

            // FRUTAS
            ['title' => 'Plátano', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.89, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.23, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Manzana', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.52, 'protein_per_gram' => 0.003, 'carbs_per_gram' => 0.14, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Naranja', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.47, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.12, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Limón', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.29, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.09, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Pera', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.57, 'protein_per_gram' => 0.004, 'carbs_per_gram' => 0.15, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Fresa', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.32, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.077, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Uva', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.69, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.18, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Melocotón', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.39, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.095, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Cereza', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.63, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.16, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Sandía', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.30, 'protein_per_gram' => 0.006, 'carbs_per_gram' => 0.076, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Melón', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.34, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.082, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Kiwi', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.61, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.15, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Piña', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.50, 'protein_per_gram' => 0.005, 'carbs_per_gram' => 0.13, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Mango', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.60, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.15, 'fat_per_gram' => 0.004, 'status' => 1],

            // FRUTOS SECOS Y GRASAS
            ['title' => 'Almendra', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.79, 'protein_per_gram' => 0.21, 'carbs_per_gram' => 0.22, 'fat_per_gram' => 0.50, 'status' => 1],
            ['title' => 'Nuez', 'ingredient_category_id' => 8, 'calories_per_gram' => 6.54, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0.14, 'fat_per_gram' => 0.65, 'status' => 1],
            ['title' => 'Avellana', 'ingredient_category_id' => 8, 'calories_per_gram' => 6.28, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0.17, 'fat_per_gram' => 0.61, 'status' => 1],
            ['title' => 'Cacahuete', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.67, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0.16, 'fat_per_gram' => 0.49, 'status' => 1],
            ['title' => 'Piñón', 'ingredient_category_id' => 8, 'calories_per_gram' => 6.73, 'protein_per_gram' => 0.14, 'carbs_per_gram' => 0.13, 'fat_per_gram' => 0.68, 'status' => 1],
            ['title' => 'Pistacho', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.60, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0.28, 'fat_per_gram' => 0.45, 'status' => 1],
            ['title' => 'Nueces', 'ingredient_category_id' => 8, 'calories_per_gram' => 6.54, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0.14, 'fat_per_gram' => 0.65, 'status' => 1],
            ['title' => 'Pasas', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.99, 'protein_per_gram' => 0.031, 'carbs_per_gram' => 0.79, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Aceite de oliva', 'ingredient_category_id' => 6, 'calories_per_gram' => 8.84, 'protein_per_gram' => 0, 'carbs_per_gram' => 0, 'fat_per_gram' => 1, 'status' => 1],
            ['title' => 'Aceite', 'ingredient_category_id' => 6, 'calories_per_gram' => 8.84, 'protein_per_gram' => 0, 'carbs_per_gram' => 0, 'fat_per_gram' => 1, 'status' => 1],
            ['title' => 'Aguacate', 'ingredient_category_id' => 6, 'calories_per_gram' => 1.60, 'protein_per_gram' => 0.02, 'carbs_per_gram' => 0.09, 'fat_per_gram' => 0.15, 'status' => 1],

            // OTROS
            ['title' => 'Azúcar', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.87, 'protein_per_gram' => 0, 'carbs_per_gram' => 1, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Miel', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.04, 'protein_per_gram' => 0.003, 'carbs_per_gram' => 0.82, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Chocolate', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.46, 'protein_per_gram' => 0.049, 'carbs_per_gram' => 0.61, 'fat_per_gram' => 0.31, 'status' => 1],
            ['title' => 'Cacao', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.28, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0.58, 'fat_per_gram' => 0.14, 'status' => 1],
            ['title' => 'Aceituna', 'ingredient_category_id' => 6, 'calories_per_gram' => 1.15, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.06, 'fat_per_gram' => 0.11, 'status' => 1],
            ['title' => 'Vinagre', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.18, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.009, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Vino', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.83, 'protein_per_gram' => 0.001, 'carbs_per_gram' => 0.027, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Cerveza', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.005, 'carbs_per_gram' => 0.036, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Caldo', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.04, 'protein_per_gram' => 0.005, 'carbs_per_gram' => 0.004, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Salsa de tomate', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.37, 'protein_per_gram' => 0.013, 'carbs_per_gram' => 0.07, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Mayonesa', 'ingredient_category_id' => 8, 'calories_per_gram' => 7.00, 'protein_per_gram' => 0.01, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.75, 'status' => 1],
            ['title' => 'Tofu', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.76, 'protein_per_gram' => 0.08, 'carbs_per_gram' => 0.019, 'fat_per_gram' => 0.048, 'status' => 1],
            ['title' => 'Soja', 'ingredient_category_id' => 8, 'calories_per_gram' => 1.73, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0.10, 'fat_per_gram' => 0.09, 'status' => 1],

            // CARNES ADICIONALES
            ['title' => 'Pato', 'ingredient_category_id' => 1, 'calories_per_gram' => 3.37, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.28, 'status' => 1],
            ['title' => 'Costilla', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.77, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.23, 'status' => 1],
            ['title' => 'Costillar', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.77, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.23, 'status' => 1],
            ['title' => 'Albóndiga', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.20, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0.08, 'fat_per_gram' => 0.14, 'status' => 1],
            ['title' => 'Anchoa', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.10, 'protein_per_gram' => 0.29, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.10, 'status' => 1],
            ['title' => 'Boquerón', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.41, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.07, 'status' => 1],
            ['title' => 'Rape', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.79, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Marisco', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.90, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.011, 'status' => 1],
            ['title' => 'Surimi', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.99, 'protein_per_gram' => 0.10, 'carbs_per_gram' => 0.12, 'fat_per_gram' => 0.02, 'status' => 1],
            ['title' => 'Caballa', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.00, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.14, 'status' => 1],

            // VERDURAS Y HORTALIZAS (ampliación)
            ['title' => 'Rúcula', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.25, 'protein_per_gram' => 0.026, 'carbs_per_gram' => 0.037, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Berros', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.11, 'protein_per_gram' => 0.026, 'carbs_per_gram' => 0.004, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Endibia', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.17, 'protein_per_gram' => 0.0125, 'carbs_per_gram' => 0.033, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Escarola', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.20, 'protein_per_gram' => 0.013, 'carbs_per_gram' => 0.036, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Canónigo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.21, 'protein_per_gram' => 0.02, 'carbs_per_gram' => 0.033, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Nabo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.28, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.064, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Rábano', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.16, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.034, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Repollo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.25, 'protein_per_gram' => 0.013, 'carbs_per_gram' => 0.056, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Lombarda', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.31, 'protein_per_gram' => 0.014, 'carbs_per_gram' => 0.074, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Cardo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.17, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.029, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Borraja', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.21, 'protein_per_gram' => 0.018, 'carbs_per_gram' => 0.035, 'fat_per_gram' => 0.006, 'status' => 1],
            ['title' => 'Níscalo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.26, 'protein_per_gram' => 0.024, 'carbs_per_gram' => 0.026, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Trufa', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.85, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.005, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Perejil', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.36, 'protein_per_gram' => 0.03, 'carbs_per_gram' => 0.063, 'fat_per_gram' => 0.008, 'status' => 1],
            ['title' => 'Cilantro', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.23, 'protein_per_gram' => 0.021, 'carbs_per_gram' => 0.037, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Albahaca', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.44, 'protein_per_gram' => 0.041, 'carbs_per_gram' => 0.027, 'fat_per_gram' => 0.019, 'status' => 1],
            ['title' => 'Orégano', 'ingredient_category_id' => 2, 'calories_per_gram' => 3.06, 'protein_per_gram' => 0.11, 'carbs_per_gram' => 0.69, 'fat_per_gram' => 0.10, 'status' => 1],
            ['title' => 'Romero', 'ingredient_category_id' => 2, 'calories_per_gram' => 1.31, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.207, 'fat_per_gram' => 0.059, 'status' => 1],
            ['title' => 'Tomillo', 'ingredient_category_id' => 2, 'calories_per_gram' => 1.01, 'protein_per_gram' => 0.056, 'carbs_per_gram' => 0.245, 'fat_per_gram' => 0.017, 'status' => 1],
            ['title' => 'Laurel', 'ingredient_category_id' => 2, 'calories_per_gram' => 3.13, 'protein_per_gram' => 0.076, 'carbs_per_gram' => 0.75, 'fat_per_gram' => 0.084, 'status' => 1],
            ['title' => 'Eneldo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.07, 'fat_per_gram' => 0.011, 'status' => 1],
            ['title' => 'Menta', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.70, 'protein_per_gram' => 0.038, 'carbs_per_gram' => 0.149, 'fat_per_gram' => 0.009, 'status' => 1],
            ['title' => 'Hierbabuena', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.44, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.084, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Cebollino', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.30, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.044, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Chalota', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.72, 'protein_per_gram' => 0.025, 'carbs_per_gram' => 0.168, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Ajo tierno', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.30, 'protein_per_gram' => 0.019, 'carbs_per_gram' => 0.05, 'fat_per_gram' => 0.006, 'status' => 1],
            ['title' => 'Tirabeque', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.42, 'protein_per_gram' => 0.028, 'carbs_per_gram' => 0.076, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Coles de Bruselas', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.034, 'carbs_per_gram' => 0.089, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Kale', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.49, 'protein_per_gram' => 0.043, 'carbs_per_gram' => 0.088, 'fat_per_gram' => 0.009, 'status' => 1],
            ['title' => 'Cebolla roja', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.40, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.093, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Tomate cherry', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.18, 'protein_per_gram' => 0.009, 'carbs_per_gram' => 0.039, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Tomate triturado', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.30, 'protein_per_gram' => 0.013, 'carbs_per_gram' => 0.06, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Pimiento del piquillo', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.27, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.05, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Pimiento morrón', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.31, 'protein_per_gram' => 0.01, 'carbs_per_gram' => 0.06, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Maíz dulce', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.86, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.19, 'fat_per_gram' => 0.014, 'status' => 1],
            ['title' => 'Champiñones', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.22, 'protein_per_gram' => 0.031, 'carbs_per_gram' => 0.033, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Boletus', 'ingredient_category_id' => 2, 'calories_per_gram' => 0.30, 'protein_per_gram' => 0.04, 'carbs_per_gram' => 0.04, 'fat_per_gram' => 0.004, 'status' => 1],

            // FRUTAS (ampliación)
            ['title' => 'Albaricoque', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.48, 'protein_per_gram' => 0.014, 'carbs_per_gram' => 0.11, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Ciruela', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.46, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.114, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Granada', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.83, 'protein_per_gram' => 0.017, 'carbs_per_gram' => 0.187, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Frambuesa', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.52, 'protein_per_gram' => 0.012, 'carbs_per_gram' => 0.119, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Mora', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.014, 'carbs_per_gram' => 0.096, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Arándano', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.57, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.145, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Coco', 'ingredient_category_id' => 3, 'calories_per_gram' => 3.54, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.152, 'fat_per_gram' => 0.335, 'status' => 1],
            ['title' => 'Coco rallado', 'ingredient_category_id' => 3, 'calories_per_gram' => 6.60, 'protein_per_gram' => 0.069, 'carbs_per_gram' => 0.237, 'fat_per_gram' => 0.645, 'status' => 1],
            ['title' => 'Papaya', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.005, 'carbs_per_gram' => 0.108, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Chirimoya', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.75, 'protein_per_gram' => 0.016, 'carbs_per_gram' => 0.177, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Pomelo', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.42, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.107, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Mandarina', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.53, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.133, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Nectarina', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.44, 'protein_per_gram' => 0.011, 'carbs_per_gram' => 0.105, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Higo', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.74, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.192, 'fat_per_gram' => 0.003, 'status' => 1],
            ['title' => 'Higos secos', 'ingredient_category_id' => 3, 'calories_per_gram' => 2.49, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.639, 'fat_per_gram' => 0.010, 'status' => 1],
            ['title' => 'Caqui', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.70, 'protein_per_gram' => 0.006, 'carbs_per_gram' => 0.186, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Membrillo', 'ingredient_category_id' => 3, 'calories_per_gram' => 0.57, 'protein_per_gram' => 0.004, 'carbs_per_gram' => 0.153, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Dátil', 'ingredient_category_id' => 3, 'calories_per_gram' => 2.82, 'protein_per_gram' => 0.025, 'carbs_per_gram' => 0.75, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Dátiles', 'ingredient_category_id' => 3, 'calories_per_gram' => 2.82, 'protein_per_gram' => 0.025, 'carbs_per_gram' => 0.75, 'fat_per_gram' => 0.004, 'status' => 1],
            ['title' => 'Coco fresco', 'ingredient_category_id' => 3, 'calories_per_gram' => 3.54, 'protein_per_gram' => 0.033, 'carbs_per_gram' => 0.152, 'fat_per_gram' => 0.335, 'status' => 1],

            // CARNES (ampliación)
            ['title' => 'Solomillo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.33, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.028, 'status' => 1],
            ['title' => 'Solomillo de cerdo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.43, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Lomo de cerdo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.43, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Lomo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.43, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Entrecot', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.71, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.20, 'status' => 1],
            ['title' => 'Entrecôte', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.71, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.20, 'status' => 1],
            ['title' => 'Chuleta', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.31, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.15, 'status' => 1],
            ['title' => 'Presa ibérica', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.00, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.13, 'status' => 1],
            ['title' => 'Secreto ibérico', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.20, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.15, 'status' => 1],
            ['title' => 'Codorniz', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.92, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.11, 'status' => 1],
            ['title' => 'Perdiz', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.34, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.03, 'status' => 1],
            ['title' => 'Jabalí', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.22, 'protein_per_gram' => 0.21, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Venado', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.30, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.034, 'status' => 1],
            ['title' => 'Morcilla', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.85, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.24, 'status' => 1],
            ['title' => 'Panceta', 'ingredient_category_id' => 1, 'calories_per_gram' => 5.18, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.53, 'status' => 1],
            ['title' => 'Salchichón', 'ingredient_category_id' => 1, 'calories_per_gram' => 4.35, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.37, 'status' => 1],
            ['title' => 'Fuet', 'ingredient_category_id' => 1, 'calories_per_gram' => 4.35, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.37, 'status' => 1],
            ['title' => 'Butifarra', 'ingredient_category_id' => 1, 'calories_per_gram' => 3.20, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0.01, 'fat_per_gram' => 0.27, 'status' => 1],
            ['title' => 'Molleja', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.02, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.035, 'status' => 1],
            ['title' => 'Hígado', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.35, 'protein_per_gram' => 0.21, 'carbs_per_gram' => 0.039, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Hígado de pollo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.16, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0.007, 'fat_per_gram' => 0.048, 'status' => 1],
            ['title' => 'Callos', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.00, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Rabo de toro', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.50, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.07, 'status' => 1],
            ['title' => 'Pechuga de pavo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.35, 'protein_per_gram' => 0.30, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Filete de ternera', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.97, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.10, 'status' => 1],
            ['title' => 'Chuletón', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.71, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.20, 'status' => 1],

            // PESCADOS Y MARISCOS (ampliación)
            ['title' => 'Rodaballo', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.95, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.03, 'status' => 1],
            ['title' => 'Lenguado', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.91, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Dorada', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.96, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.015, 'status' => 1],
            ['title' => 'Lubina', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.97, 'protein_per_gram' => 0.184, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.026, 'status' => 1],
            ['title' => 'Trucha', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.19, 'protein_per_gram' => 0.208, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.035, 'status' => 1],
            ['title' => 'Bonito', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.58, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.06, 'status' => 1],
            ['title' => 'Jurel', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.34, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.06, 'status' => 1],
            ['title' => 'Congrio', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.92, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.014, 'status' => 1],
            ['title' => 'Pez espada', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.21, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.043, 'status' => 1],
            ['title' => 'Emperador', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.21, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.043, 'status' => 1],
            ['title' => 'Besugo', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.97, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.02, 'status' => 1],
            ['title' => 'Pargo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.28, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.03, 'status' => 1],
            ['title' => 'Salmón ahumado', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.42, 'protein_per_gram' => 0.21, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.06, 'status' => 1],
            ['title' => 'Atún rojo', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.44, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.05, 'status' => 1],
            ['title' => 'Ventresca', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.00, 'protein_per_gram' => 0.22, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.12, 'status' => 1],
            ['title' => 'Mojama', 'ingredient_category_id' => 1, 'calories_per_gram' => 2.80, 'protein_per_gram' => 0.40, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.12, 'status' => 1],
            ['title' => 'Cigala', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.87, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0.002, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Langosta', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.90, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Bogavante', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.92, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.015, 'status' => 1],
            ['title' => 'Centollo', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.87, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0.002, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Nécora', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.87, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0.002, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Cangrejo', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.87, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Vieira', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.92, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0.054, 'fat_per_gram' => 0.008, 'status' => 1],
            ['title' => 'Zamburiña', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.92, 'protein_per_gram' => 0.17, 'carbs_per_gram' => 0.054, 'fat_per_gram' => 0.008, 'status' => 1],
            ['title' => 'Ostra', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.81, 'protein_per_gram' => 0.095, 'carbs_per_gram' => 0.042, 'fat_per_gram' => 0.023, 'status' => 1],
            ['title' => 'Berberecho', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.74, 'protein_per_gram' => 0.14, 'carbs_per_gram' => 0.015, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Navaja', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.89, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Percebe', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.80, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.02, 'status' => 1],
            ['title' => 'Sepia', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.79, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0.007, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Chipirón', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.92, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0.003, 'fat_per_gram' => 0.009, 'status' => 1],
            ['title' => 'Gallo', 'ingredient_category_id' => 1, 'calories_per_gram' => 0.91, 'protein_per_gram' => 0.19, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Salmónete', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.24, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.04, 'status' => 1],
            ['title' => 'Anguila', 'ingredient_category_id' => 1, 'calories_per_gram' => 1.84, 'protein_per_gram' => 0.18, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.12, 'status' => 1],

            // LÁCTEOS (ampliación)
            ['title' => 'Queso manchego', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.76, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0.015, 'fat_per_gram' => 0.30, 'status' => 1],
            ['title' => 'Queso curado', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.76, 'protein_per_gram' => 0.26, 'carbs_per_gram' => 0.015, 'fat_per_gram' => 0.30, 'status' => 1],
            ['title' => 'Queso semicurado', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.30, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0.015, 'fat_per_gram' => 0.26, 'status' => 1],
            ['title' => 'Queso azul', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.53, 'protein_per_gram' => 0.21, 'carbs_per_gram' => 0.023, 'fat_per_gram' => 0.28, 'status' => 1],
            ['title' => 'Queso de cabra', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.00, 'protein_per_gram' => 0.20, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.23, 'status' => 1],
            ['title' => 'Queso feta', 'ingredient_category_id' => 5, 'calories_per_gram' => 2.64, 'protein_per_gram' => 0.142, 'carbs_per_gram' => 0.041, 'fat_per_gram' => 0.213, 'status' => 1],
            ['title' => 'Ricotta', 'ingredient_category_id' => 5, 'calories_per_gram' => 1.74, 'protein_per_gram' => 0.113, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.13, 'status' => 1],
            ['title' => 'Mascarpone', 'ingredient_category_id' => 5, 'calories_per_gram' => 4.29, 'protein_per_gram' => 0.048, 'carbs_per_gram' => 0.05, 'fat_per_gram' => 0.44, 'status' => 1],
            ['title' => 'Burrata', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.18, 'protein_per_gram' => 0.15, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0.27, 'status' => 1],
            ['title' => 'Kéfir', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.60, 'protein_per_gram' => 0.032, 'carbs_per_gram' => 0.048, 'fat_per_gram' => 0.032, 'status' => 1],
            ['title' => 'Cuajada', 'ingredient_category_id' => 5, 'calories_per_gram' => 0.98, 'protein_per_gram' => 0.045, 'carbs_per_gram' => 0.05, 'fat_per_gram' => 0.065, 'status' => 1],
            ['title' => 'Nata líquida', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.40, 'protein_per_gram' => 0.025, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.35, 'status' => 1],
            ['title' => 'Crema fresca', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.40, 'protein_per_gram' => 0.025, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.35, 'status' => 1],
            ['title' => 'Leche evaporada', 'ingredient_category_id' => 5, 'calories_per_gram' => 1.34, 'protein_per_gram' => 0.068, 'carbs_per_gram' => 0.10, 'fat_per_gram' => 0.075, 'status' => 1],
            ['title' => 'Leche condensada', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.21, 'protein_per_gram' => 0.079, 'carbs_per_gram' => 0.54, 'fat_per_gram' => 0.087, 'status' => 1],
            ['title' => 'Queso crema', 'ingredient_category_id' => 5, 'calories_per_gram' => 3.42, 'protein_per_gram' => 0.06, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0.34, 'status' => 1],

            // CEREALES Y GRANOS (ampliación)
            ['title' => 'Quinoa', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.68, 'protein_per_gram' => 0.141, 'carbs_per_gram' => 0.642, 'fat_per_gram' => 0.061, 'status' => 1],
            ['title' => 'Cuscús', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.76, 'protein_per_gram' => 0.128, 'carbs_per_gram' => 0.774, 'fat_per_gram' => 0.006, 'status' => 1],
            ['title' => 'Bulgur', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.42, 'protein_per_gram' => 0.123, 'carbs_per_gram' => 0.759, 'fat_per_gram' => 0.013, 'status' => 1],
            ['title' => 'Espelta', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.38, 'protein_per_gram' => 0.146, 'carbs_per_gram' => 0.702, 'fat_per_gram' => 0.024, 'status' => 1],
            ['title' => 'Arroz integral', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.70, 'protein_per_gram' => 0.079, 'carbs_per_gram' => 0.772, 'fat_per_gram' => 0.029, 'status' => 1],
            ['title' => 'Arroz basmati', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.60, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.79, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Arroz bomba', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.60, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.79, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Sémola', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.60, 'protein_per_gram' => 0.13, 'carbs_per_gram' => 0.72, 'fat_per_gram' => 0.01, 'status' => 1],
            ['title' => 'Polenta', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.70, 'protein_per_gram' => 0.087, 'carbs_per_gram' => 0.78, 'fat_per_gram' => 0.013, 'status' => 1],
            ['title' => 'Palomitas', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.87, 'protein_per_gram' => 0.12, 'carbs_per_gram' => 0.78, 'fat_per_gram' => 0.045, 'status' => 1],
            ['title' => 'Harina integral', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.40, 'protein_per_gram' => 0.132, 'carbs_per_gram' => 0.72, 'fat_per_gram' => 0.025, 'status' => 1],
            ['title' => 'Harina de maíz', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.61, 'protein_per_gram' => 0.069, 'carbs_per_gram' => 0.769, 'fat_per_gram' => 0.039, 'status' => 1],
            ['title' => 'Harina de arroz', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.66, 'protein_per_gram' => 0.059, 'carbs_per_gram' => 0.801, 'fat_per_gram' => 0.014, 'status' => 1],
            ['title' => 'Harina de almendra', 'ingredient_category_id' => 4, 'calories_per_gram' => 5.81, 'protein_per_gram' => 0.214, 'carbs_per_gram' => 0.216, 'fat_per_gram' => 0.499, 'status' => 1],
            ['title' => 'Harina de coco', 'ingredient_category_id' => 4, 'calories_per_gram' => 4.43, 'protein_per_gram' => 0.184, 'carbs_per_gram' => 0.566, 'fat_per_gram' => 0.168, 'status' => 1],
            ['title' => 'Harina de garbanzo', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.87, 'protein_per_gram' => 0.224, 'carbs_per_gram' => 0.578, 'fat_per_gram' => 0.067, 'status' => 1],
            ['title' => 'Pan de molde', 'ingredient_category_id' => 4, 'calories_per_gram' => 2.66, 'protein_per_gram' => 0.089, 'carbs_per_gram' => 0.495, 'fat_per_gram' => 0.034, 'status' => 1],
            ['title' => 'Pan de centeno', 'ingredient_category_id' => 4, 'calories_per_gram' => 2.59, 'protein_per_gram' => 0.085, 'carbs_per_gram' => 0.483, 'fat_per_gram' => 0.033, 'status' => 1],
            ['title' => 'Pan de pita', 'ingredient_category_id' => 4, 'calories_per_gram' => 2.75, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.55, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Pan rallado', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.95, 'protein_per_gram' => 0.133, 'carbs_per_gram' => 0.715, 'fat_per_gram' => 0.053, 'status' => 1],
            ['title' => 'Panko', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.95, 'protein_per_gram' => 0.13, 'carbs_per_gram' => 0.70, 'fat_per_gram' => 0.06, 'status' => 1],
            ['title' => 'Maicena', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.57, 'protein_per_gram' => 0.003, 'carbs_per_gram' => 0.91, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Copos de avena', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.89, 'protein_per_gram' => 0.169, 'carbs_per_gram' => 0.663, 'fat_per_gram' => 0.069, 'status' => 1],
            ['title' => 'Granola', 'ingredient_category_id' => 4, 'calories_per_gram' => 4.71, 'protein_per_gram' => 0.10, 'carbs_per_gram' => 0.64, 'fat_per_gram' => 0.21, 'status' => 1],
            ['title' => 'Tortilla de maíz', 'ingredient_category_id' => 4, 'calories_per_gram' => 2.18, 'protein_per_gram' => 0.057, 'carbs_per_gram' => 0.446, 'fat_per_gram' => 0.029, 'status' => 1],
            ['title' => 'Tortilla de trigo', 'ingredient_category_id' => 4, 'calories_per_gram' => 3.00, 'protein_per_gram' => 0.084, 'carbs_per_gram' => 0.514, 'fat_per_gram' => 0.066, 'status' => 1],
            ['title' => 'Nachos', 'ingredient_category_id' => 4, 'calories_per_gram' => 5.00, 'protein_per_gram' => 0.08, 'carbs_per_gram' => 0.60, 'fat_per_gram' => 0.25, 'status' => 1],
            ['title' => 'Patatas fritas', 'ingredient_category_id' => 4, 'calories_per_gram' => 5.36, 'protein_per_gram' => 0.07, 'carbs_per_gram' => 0.53, 'fat_per_gram' => 0.34, 'status' => 1],

            // LEGUMBRES (ampliación)
            ['title' => 'Alubias blancas', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.27, 'protein_per_gram' => 0.087, 'carbs_per_gram' => 0.226, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Alubias rojas', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.27, 'protein_per_gram' => 0.087, 'carbs_per_gram' => 0.226, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Judías pintas', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.27, 'protein_per_gram' => 0.087, 'carbs_per_gram' => 0.226, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Frijoles negros', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.32, 'protein_per_gram' => 0.089, 'carbs_per_gram' => 0.237, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Edamame', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.21, 'protein_per_gram' => 0.119, 'carbs_per_gram' => 0.089, 'fat_per_gram' => 0.052, 'status' => 1],
            ['title' => 'Tempeh', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.93, 'protein_per_gram' => 0.185, 'carbs_per_gram' => 0.094, 'fat_per_gram' => 0.108, 'status' => 1],
            ['title' => 'Seitán', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.20, 'protein_per_gram' => 0.24, 'carbs_per_gram' => 0.05, 'fat_per_gram' => 0.015, 'status' => 1],
            ['title' => 'Soja texturizada', 'ingredient_category_id' => 7, 'calories_per_gram' => 3.37, 'protein_per_gram' => 0.50, 'carbs_per_gram' => 0.33, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Habas', 'ingredient_category_id' => 7, 'calories_per_gram' => 0.81, 'protein_per_gram' => 0.065, 'carbs_per_gram' => 0.136, 'fat_per_gram' => 0.006, 'status' => 1],
            ['title' => 'Garbanzos', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.39, 'protein_per_gram' => 0.089, 'carbs_per_gram' => 0.27, 'fat_per_gram' => 0.026, 'status' => 1],
            ['title' => 'Lentejas', 'ingredient_category_id' => 7, 'calories_per_gram' => 1.16, 'protein_per_gram' => 0.09, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.004, 'status' => 1],

            // FRUTOS SECOS Y SEMILLAS (ampliación)
            ['title' => 'Anacardo', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.53, 'protein_per_gram' => 0.182, 'carbs_per_gram' => 0.302, 'fat_per_gram' => 0.439, 'status' => 1],
            ['title' => 'Anacardos', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.53, 'protein_per_gram' => 0.182, 'carbs_per_gram' => 0.302, 'fat_per_gram' => 0.439, 'status' => 1],
            ['title' => 'Macadamia', 'ingredient_category_id' => 8, 'calories_per_gram' => 7.18, 'protein_per_gram' => 0.079, 'carbs_per_gram' => 0.138, 'fat_per_gram' => 0.758, 'status' => 1],
            ['title' => 'Chía', 'ingredient_category_id' => 8, 'calories_per_gram' => 4.86, 'protein_per_gram' => 0.165, 'carbs_per_gram' => 0.421, 'fat_per_gram' => 0.307, 'status' => 1],
            ['title' => 'Lino', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.34, 'protein_per_gram' => 0.183, 'carbs_per_gram' => 0.289, 'fat_per_gram' => 0.422, 'status' => 1],
            ['title' => 'Sésamo', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.73, 'protein_per_gram' => 0.177, 'carbs_per_gram' => 0.234, 'fat_per_gram' => 0.497, 'status' => 1],
            ['title' => 'Semillas de girasol', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.84, 'protein_per_gram' => 0.208, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.515, 'status' => 1],
            ['title' => 'Semillas de calabaza', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.59, 'protein_per_gram' => 0.302, 'carbs_per_gram' => 0.107, 'fat_per_gram' => 0.49, 'status' => 1],
            ['title' => 'Tahini', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.95, 'protein_per_gram' => 0.178, 'carbs_per_gram' => 0.212, 'fat_per_gram' => 0.537, 'status' => 1],
            ['title' => 'Mantequilla de cacahuete', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.88, 'protein_per_gram' => 0.25, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.50, 'status' => 1],
            ['title' => 'Piñones', 'ingredient_category_id' => 8, 'calories_per_gram' => 6.73, 'protein_per_gram' => 0.14, 'carbs_per_gram' => 0.13, 'fat_per_gram' => 0.68, 'status' => 1],

            // ESPECIAS Y CONDIMENTOS (ampliación)
            ['title' => 'Pimentón', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.82, 'protein_per_gram' => 0.141, 'carbs_per_gram' => 0.539, 'fat_per_gram' => 0.129, 'status' => 1],
            ['title' => 'Pimentón dulce', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.82, 'protein_per_gram' => 0.141, 'carbs_per_gram' => 0.539, 'fat_per_gram' => 0.129, 'status' => 1],
            ['title' => 'Pimentón picante', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.18, 'protein_per_gram' => 0.12, 'carbs_per_gram' => 0.60, 'fat_per_gram' => 0.17, 'status' => 1],
            ['title' => 'Comino', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.75, 'protein_per_gram' => 0.178, 'carbs_per_gram' => 0.442, 'fat_per_gram' => 0.223, 'status' => 1],
            ['title' => 'Cúrcuma', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.54, 'protein_per_gram' => 0.078, 'carbs_per_gram' => 0.65, 'fat_per_gram' => 0.099, 'status' => 1],
            ['title' => 'Jengibre', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.80, 'protein_per_gram' => 0.018, 'carbs_per_gram' => 0.178, 'fat_per_gram' => 0.008, 'status' => 1],
            ['title' => 'Nuez moscada', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.25, 'protein_per_gram' => 0.058, 'carbs_per_gram' => 0.493, 'fat_per_gram' => 0.363, 'status' => 1],
            ['title' => 'Canela', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.47, 'protein_per_gram' => 0.04, 'carbs_per_gram' => 0.806, 'fat_per_gram' => 0.012, 'status' => 1],
            ['title' => 'Clavo', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.74, 'protein_per_gram' => 0.06, 'carbs_per_gram' => 0.655, 'fat_per_gram' => 0.13, 'status' => 1],
            ['title' => 'Cardamomo', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.11, 'protein_per_gram' => 0.108, 'carbs_per_gram' => 0.685, 'fat_per_gram' => 0.067, 'status' => 1],
            ['title' => 'Anís estrellado', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.37, 'protein_per_gram' => 0.176, 'carbs_per_gram' => 0.50, 'fat_per_gram' => 0.159, 'status' => 1],
            ['title' => 'Vainilla', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.88, 'protein_per_gram' => 0.001, 'carbs_per_gram' => 0.127, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Azafrán', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.10, 'protein_per_gram' => 0.114, 'carbs_per_gram' => 0.654, 'fat_per_gram' => 0.059, 'status' => 1],
            ['title' => 'Pimienta', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.51, 'protein_per_gram' => 0.104, 'carbs_per_gram' => 0.639, 'fat_per_gram' => 0.033, 'status' => 1],
            ['title' => 'Pimienta negra', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.51, 'protein_per_gram' => 0.104, 'carbs_per_gram' => 0.639, 'fat_per_gram' => 0.033, 'status' => 1],
            ['title' => 'Guindilla', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.18, 'protein_per_gram' => 0.12, 'carbs_per_gram' => 0.60, 'fat_per_gram' => 0.17, 'status' => 1],
            ['title' => 'Cayena', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.18, 'protein_per_gram' => 0.12, 'carbs_per_gram' => 0.60, 'fat_per_gram' => 0.17, 'status' => 1],
            ['title' => 'Mostaza', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.66, 'protein_per_gram' => 0.044, 'carbs_per_gram' => 0.058, 'fat_per_gram' => 0.033, 'status' => 1],
            ['title' => 'Ketchup', 'ingredient_category_id' => 8, 'calories_per_gram' => 1.01, 'protein_per_gram' => 0.012, 'carbs_per_gram' => 0.258, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Salsa de soja', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.53, 'protein_per_gram' => 0.08, 'carbs_per_gram' => 0.049, 'fat_per_gram' => 0.006, 'status' => 1],
            ['title' => 'Curry', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.25, 'protein_per_gram' => 0.14, 'carbs_per_gram' => 0.55, 'fat_per_gram' => 0.14, 'status' => 1],
            ['title' => 'Pasta de tomate', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.82, 'protein_per_gram' => 0.043, 'carbs_per_gram' => 0.189, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Tomate frito', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.70, 'protein_per_gram' => 0.015, 'carbs_per_gram' => 0.09, 'fat_per_gram' => 0.03, 'status' => 1],
            ['title' => 'Salsa barbacoa', 'ingredient_category_id' => 8, 'calories_per_gram' => 1.72, 'protein_per_gram' => 0.008, 'carbs_per_gram' => 0.40, 'fat_per_gram' => 0.005, 'status' => 1],
            ['title' => 'Sirope de arce', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.60, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.67, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Mermelada', 'ingredient_category_id' => 8, 'calories_per_gram' => 2.50, 'protein_per_gram' => 0.004, 'carbs_per_gram' => 0.65, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Ajo en polvo', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.31, 'protein_per_gram' => 0.166, 'carbs_per_gram' => 0.727, 'fat_per_gram' => 0.007, 'status' => 1],
            ['title' => 'Levadura', 'ingredient_category_id' => 8, 'calories_per_gram' => 1.05, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.019, 'status' => 1],
            ['title' => 'Levadura de panadero', 'ingredient_category_id' => 8, 'calories_per_gram' => 1.05, 'protein_per_gram' => 0.16, 'carbs_per_gram' => 0.20, 'fat_per_gram' => 0.019, 'status' => 1],
            ['title' => 'Levadura química', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.53, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.28, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Gelatina', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.35, 'protein_per_gram' => 0.85, 'carbs_per_gram' => 0, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Agar agar', 'ingredient_category_id' => 8, 'calories_per_gram' => 3.06, 'protein_per_gram' => 0.062, 'carbs_per_gram' => 0.809, 'fat_per_gram' => 0.001, 'status' => 1],

            // CHOCOLATE Y DULCES (ampliación)
            ['title' => 'Chocolate con leche', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.35, 'protein_per_gram' => 0.077, 'carbs_per_gram' => 0.594, 'fat_per_gram' => 0.297, 'status' => 1],
            ['title' => 'Chocolate blanco', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.39, 'protein_per_gram' => 0.059, 'carbs_per_gram' => 0.59, 'fat_per_gram' => 0.32, 'status' => 1],
            ['title' => 'Chocolate negro', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.46, 'protein_per_gram' => 0.049, 'carbs_per_gram' => 0.61, 'fat_per_gram' => 0.31, 'status' => 1],
            ['title' => 'Turrón', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.00, 'protein_per_gram' => 0.12, 'carbs_per_gram' => 0.55, 'fat_per_gram' => 0.26, 'status' => 1],
            ['title' => 'Mazapán', 'ingredient_category_id' => 8, 'calories_per_gram' => 4.38, 'protein_per_gram' => 0.08, 'carbs_per_gram' => 0.64, 'fat_per_gram' => 0.18, 'status' => 1],
            ['title' => 'Polvorón', 'ingredient_category_id' => 8, 'calories_per_gram' => 5.20, 'protein_per_gram' => 0.06, 'carbs_per_gram' => 0.50, 'fat_per_gram' => 0.32, 'status' => 1],

            // BEBIDAS Y OTROS
            ['title' => 'Agua', 'ingredient_category_id' => 8, 'calories_per_gram' => 0, 'protein_per_gram' => 0, 'carbs_per_gram' => 0, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Zumo de naranja', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.45, 'protein_per_gram' => 0.007, 'carbs_per_gram' => 0.104, 'fat_per_gram' => 0.002, 'status' => 1],
            ['title' => 'Refresco', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.42, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.106, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Cerveza', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.43, 'protein_per_gram' => 0.005, 'carbs_per_gram' => 0.036, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Vino blanco', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.82, 'protein_per_gram' => 0.001, 'carbs_per_gram' => 0.026, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Vino tinto', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.85, 'protein_per_gram' => 0.001, 'carbs_per_gram' => 0.027, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Cava', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.70, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.02, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Sidra', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.55, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.03, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Café', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.02, 'protein_per_gram' => 0.001, 'carbs_per_gram' => 0, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Té', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.01, 'protein_per_gram' => 0, 'carbs_per_gram' => 0.003, 'fat_per_gram' => 0, 'status' => 1],
            ['title' => 'Caldo de verduras', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.04, 'protein_per_gram' => 0.005, 'carbs_per_gram' => 0.004, 'fat_per_gram' => 0.001, 'status' => 1],
            ['title' => 'Caldo de pollo', 'ingredient_category_id' => 8, 'calories_per_gram' => 0.05, 'protein_per_gram' => 0.006, 'carbs_per_gram' => 0.004, 'fat_per_gram' => 0.001, 'status' => 1],
        ];

        foreach ($ingredients as $ing) {
            Ingredient::firstOrCreate(
                ['title' => $ing['title']],
                $ing
            );
        }

        $this->command?->info('Ingredients seeded: ' . Ingredient::count() . ' total');
    }
}
